# This notebook does time series cross validation.

In [221]:
import pandas as pd
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

In [222]:
DATA_PATH = '../data/data.csv'
df = pd.read_csv(DATA_PATH)

In [277]:
start = 2
temp = pd.DataFrame([1,2,3,4,5])
a = temp.loc[:start].copy()
b = temp.loc[start + 1:].copy()

print(len(temp))
print(a)
print(b)

5
   0
0  1
1  2
2  3
   0
3  4
4  5


In [223]:
# Only obtain the labeled rows
df = df[~df['shot_made_flag'].isnull()]
df.shape

(25697, 25)

In [224]:
def extract_test_set(df, split=0.8):
    """Returns a tuple with the train/validation and test set on a given split.
    """
    n_rows = df.shape[0]
    start = int(n_rows * split)
    
    train_validation_set = df[:start]
    test_set = df[start:]
    
    assert train_validation_set.shape[0] + test_set.shape[0] == n_rows
    return train_validation_set, test_set
    
train_validation_set, test_set = extract_test_set(df)

In [228]:
print(len(test_set))

5140


In [225]:
# split into input (X) and output (Y) variables
X = train_validation_set[train_validation_set.columns.difference(['shot_made_flag'])]
Y = train_validation_set['shot_made_flag']

In [229]:
def train_validation_split(X: pd.DataFrame, verbose=False):
    splits = TimeSeriesSplit(n_splits=3)
    X.loc[:, 'index'] = X.index  # Add dataframe index as a column
    X = X.to_numpy()
    index_column_number = 24  # Column number of the index column
    
    for train_index, validation_index in splits.split(X):
        train = X[train_index]
        validation = X[validation_index]
        
        if verbose:
            print(train[:, index_column_number])
            print(validation[:, index_column_number])

            print(f'Observations: {len(train) + len(validation)}')
            print(f'Training Observations: {len(train)}'
                  f' First index: {train[0][index_column_number]} Last index: {train[len(train) - 1][index_column_number]}')
            print(f'Validation Observations: {len(validation)}'
                  f' First index: {validation[0][index_column_number]} Last index: {validation[len(validation) - 1][index_column_number]}\n')
        yield train, validation

In [230]:
# Example usage

accs = []

for train, validation in train_validation_split(X, verbose=True):
    pass
    # print(train, validation)
#     train = preprocess(train)
#     validation = preprocess(validation)
    
#     model = knn.fit(train, Y_train)
#     accuracy = model.validate(validation, Y_validation)
#     accs.append(accuracy)
    
# total_accuracy_k1 = accs.avg()
# total_accuracy_k2 = accs.avg()
# total_accuracy_k3 = accs.avg()

# best = max([total_accuracy_k1,total_accuracy_k2,total_accuracy_k3 ])

# best_model.validate(test, y_test)

# # FINAL SCORE!!!

[1 2 3 ... 6118 6119 6120]
[6121 6122 6124 ... 12269 12270 12271]
Observations: 10279
Training Observations: 5140 First index: 1 Last index: 6120
Validation Observations: 5139 First index: 6121 Last index: 12271

[1 2 3 ... 12269 12270 12271]
[12272 12273 12274 ... 18385 18386 18387]
Observations: 15418
Training Observations: 10279 First index: 1 Last index: 12271
Validation Observations: 5139 First index: 12272 Last index: 18387

[1 2 3 ... 18385 18386 18387]
[18388 18389 18391 ... 24533 24534 24535]
Observations: 20557
Training Observations: 15418 First index: 1 Last index: 18387
Validation Observations: 5139 First index: 18388 Last index: 24535



In [ ]:
split = Split(csv_path='../data/data.csv')

for train, validation in split.train_validation_split():
    # do stuff
    pass


best_model.validate(split.test_set, split.test_set['shot_made_flag'])